project_id = "gcp-ci-cd-drugs-data-pipeline"
project_name = "gcp_ci_cd_drugs_data_pipeline"
billing_account = "01403B-81DEB7-D4554D"
org_id = ""
location = "US"
github_owner = "itervore"
github_repo = "gcp_ci_cd_drugs_data_pipeline"